version: "3"
services:
  mc:
    image: itzg/minecraft-server:java8
    restart: always
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      TYPE: "CURSEFORGE"
      MEMORY: "5G"
      CF_SERVER_MOD: "MC-Eternal-Lite-1.3.8-SERVER.zip"

    volumes:
      # attach the relative directory 'data' to the container's /data path
      - ./data:/data
    networks:
      - proxy_default

networks:
  proxy_default:
    external: true
